### ISSUE TITLE
Add why js-sdsl to `Getting Started`

### ISSUE THREAD

**Issue by ZLY201** [js-sdsl/js-sdsl.github.io#4]

**Comment by ZLY201** [comment]
done.

**Comment by ZLY201** [comment]
I think it's time to recommend Js-sdsl to more people. @noname0310

**Comment by noname0310** [comment]
By the way, has the size compare ci problem already been solved?

**Comment by ZLY201** [comment]
> By the way, has the size compare ci problem already been solved?

Not yet. That's a low priority thing.
